feat(README.md): Update `README.md`
blocksense-network/ethsofia_hackaton pull request #5
Opened 2024-10-16 14:17 UTC by EmilIvanichkovv

2024-10-16 14:23 UTC, smanilov approved these changes
LG!

2024-10-16 16:10 UTC, NikolayKostadinov21 requested changes

2024-10-16 16:10 UTC, NikolayKostadinov21 commented on README.md
> +This will launch 2 local ETH blockchains (anvil), blocksense sequencer service with is responsible for publishing oracle scripts data feeds to the ETH blockchain and one reporter which will execute y
which instead of with

2024-10-16 16:10 UTC, NikolayKostadinov21 commented on README.md
> +To run wasm revolut reporter you need to build it:
you'll need

2024-10-16 16:10 UTC, NikolayKostadinov21 commented on README.md
> +This will launch 2 local ETH blockchains (anvil), blocksense sequencer service with is responsible for publishing oracle scripts data feeds to the ETH blockchain and one reporter which will execute y
its instead of it's

2024-10-16 16:10 UTC, NikolayKostadinov21 commented on README.md
> +Start docker compose again. That will start 2 anvil instances, one sequencer and yahoo reporter
and one yahoo reporter

2024-10-16 17:04 UTC, yordanmadzhunkov approved these changes

2024-10-16 17:04 UTC, merged

2024-10-17 09:30 UTC, smanilov commented on README.md
> +To run wasm revolut reporter you need to build it:
it's ok as is